### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

### ISSUE THREAD

**Issue by ozett** [blaueck/tf-mtcnn#3]
got an error trying your project...

`AttributeError: module 'tensorflow' has no attribute 'GraphDef'`

do i need some tweaks to get it working with tensorflow 2.2 ?
appreciate some hints...thx..

![image](https://user-images.githubusercontent.com/5937811/89521071-23693e00-d7df-11ea-86eb-c0c22110d9e6.png)

**Comment by ozett** [comment]
i saw your commit-comments for tensorflow 2.x, but overlooked the file ...

https://github.com/blaueck/tf-mtcnn/blob/master/mtcnn_tfv2.py

got it working , great, thanks!

**Comment by blaueck** [comment]
glad you found it. this project it's a little messy.

**Comment by ozett** [comment]
i got i working and compared it with some of my test mtcnn
i got perfect results on my jetson nano with this: https://github.com/jkjung-avt/tensorrt_demos

but your implemtation hit it , because it recognized all faces in my test image.
great work!!!

![image](https://user-images.githubusercontent.com/5937811/89558381-714c6900-d814-11ea-9521-d9f16f946ec6.png)

**Comment by blaueck** [comment]
thanks, glad to hear that.
